package types

// RequestID represents a requestid (id which is oftern generated by the caller)
type RequestID struct {
	GenID
}

var NilRequestID = RequestID{GenID: NilID}

//CorrelationID is a id used to correlate steps which happen as part of a distributed system
type CorrelationID struct {
	GenID
}

var NilCorrelationID = CorrelationID{GenID: NilID}